[package]
name = "bt-blockchain-validators"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# Botho dependencies
bt-blockchain-types = { workspace = true }
bt-crypto-keys = { workspace = true }

# External dependencies
displaydoc = { workspace = true }
hex = { workspace = true }
pem = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
bt-blockchain-test-utils = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-test-helper = { workspace = true }

tempfile = { workspace = true }
