[package]
name = "mc-fog-ledger-enclave-edl"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
links = "ledger_enclave_edl"
license = "GPL-3.0"
rust-version = { workspace = true }

[build-dependencies]
mc-util-build-script = { workspace = true }

cargo-emit = { workspace = true }
