[package]
name = "bt-test-vectors-account-keys"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
bt-test-vectors-definitions = { workspace = true }

[build-dependencies]
bt-account-keys = { workspace = true }
bt-core = { workspace = true, features = ["bip39"] }
bt-test-vectors-definitions = { workspace = true }
bt-util-test-vector = { workspace = true }

hex = { workspace = true }
tiny-bip39 = { workspace = true }
