[package]
name = "bth-test-vectors-account-keys"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
bth-test-vectors-definitions = { workspace = true }

[build-dependencies]
bth-account-keys = { workspace = true }
bth-core = { workspace = true, features = ["bip39"] }
bth-test-vectors-definitions = { workspace = true }
bth-util-test-vector = { workspace = true }

hex = { workspace = true }
tiny-bip39 = { workspace = true }
