[package]
name = "mc-fog-view-server"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[lib]
name = "mc_fog_view_server"
path = "src/lib.rs"

[[bin]]
name = "fog_view_server"
path = "src/bin/main.rs"

[[bin]]
name = "fog_view_router"
path = "src/bin/router.rs"

[dependencies]
# third party
clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
lazy_static = { workspace = true }
prometheus = { workspace = true }

# mobilecoin
mc-api = { workspace = true }
mc-attest-api = { workspace = true }
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-crypto-keys = { workspace = true }

# fog
mc-fog-api = { workspace = true }
mc-fog-kex-rng = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-sql-recovery-db = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-uri = { workspace = true }
mc-fog-view-enclave = { workspace = true }
mc-fog-view-enclave-api = { workspace = true }
mc-sgx-report-cache-untrusted = { workspace = true }
mc-util-cli = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-metrics = { workspace = true }
mc-util-parse = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-telemetry = { workspace = true, features = ["otlp"] }
mc-util-uri = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true }

[dev-dependencies]
mc-attest-verifier = { workspace = true, features = ["std"] }
mc-attest-verifier-types = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-crypto-keys = { workspace = true }
mc-crypto-x509-test-vectors = { workspace = true }

mc-fog-test-infra = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-view-connection = { workspace = true }
mc-fog-view-enclave-measurement = { workspace = true }
mc-fog-view-protocol = { workspace = true }
mc-fog-view-server-test-utils = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-encodings = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-test-helper = { workspace = true }
mc-util-uri = { workspace = true }

portpicker = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
yare = { workspace = true }
