[package]
name = "mc-fog-ledger-enclave"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# mobilecoin
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-verifier = { workspace = true, features = ["std"] }
mc-common = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-enclave-boundary = { workspace = true }
mc-sgx-debug-edl = { workspace = true }
mc-sgx-panic-edl = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-sgx-slog-edl = { workspace = true }
mc-sgx-types = { workspace = true }
mc-sgx-urts = { workspace = true }
mc-util-serial = { workspace = true }

# fog
mc-fog-ledger-enclave-api = { workspace = true }
mc-fog-ledger-enclave-edl = { workspace = true }
mc-fog-ledger-enclave-measurement = { workspace = true }
mc-fog-ocall-oram-storage-edl = { workspace = true }
mc-fog-ocall-oram-storage-untrusted = { workspace = true }
mc-fog-types = { workspace = true }

[build-dependencies]
mc-util-build-script = { workspace = true }
mc-util-build-sgx = { workspace = true }

cargo-emit = { workspace = true }
pkg-config = { workspace = true }
