[package]
name = "bt-crypto-box"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
bt-crypto-hashes = { workspace = true }
bt-crypto-keys = { workspace = true }

aead = { workspace = true, features = ["alloc"] }
digest = { workspace = true }
displaydoc = { workspace = true }
hkdf = { workspace = true }
mc-oblivious-aes-gcm = { workspace = true, features = ["aes", "alloc", "zeroize"] }
rand_core = { workspace = true }

[dev-dependencies]
bt-util-from-random = { workspace = true }
bt-util-test-helper = { workspace = true }
