[package]
name = "mc-fog-load-testing"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "fog_ingest_server_load_test"
path = "src/bin/ingest.rs"

[dependencies]
# third party
clap = { workspace = true, features = ["derive", "env"] }
grpcio = { workspace = true, features = ["prost-codec"] }
retry = { workspace = true }
tempfile = { workspace = true }

# mc
mc-account-keys = { workspace = true }
mc-blockchain-test-utils = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-crypto-keys = { workspace = true }
mc-ledger-db = { workspace = true }
mc-rand = { workspace = true }
mc-util-build-info = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-uri = { workspace = true }
mc-watcher = { workspace = true }

# fog
mc-fog-api = { workspace = true }
mc-fog-ingest-client = { workspace = true }
mc-fog-ingest-server = { workspace = true } # This ensures the server is built
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-sql-recovery-db = { workspace = true }
mc-fog-uri = { workspace = true }
