[package]
name = "bth-transaction-summary"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[features]
std = ["prost?/std"]
serde = [
    "dep:serde",
    "bth-account-keys?/serde",
    "bth-crypto-keys/serde",
    "bth-crypto-ring-signature/serde",
    "bth-transaction-types/serde",
]
prost = [
    "dep:prost",
    "bth-account-keys?/prost",
    "bth-crypto-keys/prost",
    "bth-crypto-ring-signature/prost",
    "bth-transaction-types/prost",
]

default = ["std", "serde", "prost", "bth-account-keys"]

[dependencies]
# External dependencies
displaydoc = { workspace = true }
heapless = { workspace = true }

# Botho dependencies
bth-account-keys = { workspace = true, optional = true }
bth-core = { workspace = true }
bth-crypto-digestible = { workspace = true, features = ["dalek", "derive"] }
bth-crypto-keys = { workspace = true }
bth-crypto-ring-signature = { workspace = true }
bth-transaction-types = { workspace = true, features = ["alloc"] }
bth-util-vec-map = { workspace = true }
bth-util-zip-exact = { workspace = true }

prost = { workspace = true, features = ["prost-derive"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
subtle = { workspace = true, features = ["i128"] }
zeroize = { workspace = true }

[dev-dependencies]
bth-transaction-core = { workspace = true, features = [] }
bth-util-from-random = { workspace = true }
rand = { workspace = true }
