[package]
name = "bt-crypto-x509-test-vectors"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
description = "Utilities for generating certificates and chains for unit tests"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "bt-crypto-x509-test-vectors"
path = "src/main.rs"

[dependencies]
bt-crypto-keys = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
pem = { workspace = true }

[build-dependencies]
cargo-emit = { workspace = true }
bt-util-build-script = { workspace = true }
