[package]
name = "bt-transaction-builder"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
test-only = []
pq = ["bt-crypto-pq", "bt-account-keys/pq", "bt-transaction-core/pq"]  # Post-quantum transaction builder

[dependencies]
# External dependencies
cfg-if = { workspace = true }
displaydoc = { workspace = true }
hmac = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
sha2 = { workspace = true }
subtle = { workspace = true }
zeroize = { workspace = true }

# Botho dependencies
bt-account-keys = { workspace = true }
bt-crypto-digestible = { workspace = true }
bt-crypto-hashes = { workspace = true }
bt-crypto-keys = { workspace = true }
bt-crypto-pq = { workspace = true, optional = true }
bt-crypto-ring-signature-signer = { workspace = true }
bt-transaction-core = { workspace = true }
bt-transaction-extra = { workspace = true }
bt-transaction-summary = { workspace = true }
bt-transaction-types = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-serial = { workspace = true }
bt-util-u64-ratio = { workspace = true }

# `default` feature enables curve25519-dalek target detection for x86_64 with and without AVX
curve25519-dalek = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
maplit = { workspace = true }

bt-util-test-helper = { workspace = true }
