[package]
name = "mc-fog-ocall-oram-storage-untrusted"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-common = { workspace = true, features = ["log"] }

lazy_static = { workspace = true }
