[package]
name = "mc-util-encodings"
version = "7.1.0"
authors = ["MobileCoin"]
description = "Support for various simple encodings (hex strings, base64 strings, Intel x86_64 structures, etc.)"
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[features]
default = []
std = []

[dependencies]
mc-util-repr-bytes = { workspace = true }

base64 = { workspace = true }
displaydoc = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
