[package]
name = "mc-fog-ingest-server"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "fog_ingest_server"
path = "src/bin/main.rs"

[dependencies]
# third-party
clap = { workspace = true, features = ["derive", "env"] }
dirs = { workspace = true }
displaydoc = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
hex = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
retry = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true }

# root
mc-api = { workspace = true }
mc-attest-api = { workspace = true }
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-verifier-types = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-connection = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-ledger-db = { workspace = true }
mc-mobilecoind-api = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-sgx-report-cache-untrusted = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-cli = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-metrics = { workspace = true }
mc-util-parse = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-telemetry = { workspace = true, features = ["otlp"] }
mc-util-uri = { workspace = true }
mc-watcher = { workspace = true }
mc-watcher-api = { workspace = true }

# fog
mc-fog-api = { workspace = true }
mc-fog-block-provider = { workspace = true }
mc-fog-ingest-enclave = { workspace = true }
mc-fog-ingest-enclave-api = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-sql-recovery-db = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-uri = { workspace = true }

[dev-dependencies]
mc-fog-ingest-client = { workspace = true }
mc-fog-ingest-server-test-utils = { workspace = true }
mc-fog-test-infra = { workspace = true }
mc-util-build-info = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-test-helper = { workspace = true }

rand_core = { workspace = true }
rand_hc = { workspace = true }
url = { workspace = true }
