[package]
name = "mc-util-uri"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-common = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-util-host-cert = { workspace = true }

base64 = { workspace = true }
displaydoc = { workspace = true }
hex = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
url = { workspace = true }

[dev-dependencies]
mc-util-from-random = { workspace = true }

rand = { workspace = true }
rand_hc = { workspace = true }
