[package]
name = "bth-util-uri"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
bth-common = { workspace = true }
bth-crypto-keys = { workspace = true }
bth-util-host-cert = { workspace = true }

base64 = { workspace = true }
displaydoc = { workspace = true }
hex = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
url = { workspace = true }

[dev-dependencies]
bth-util-from-random = { workspace = true }

rand = { workspace = true }
rand_hc = { workspace = true }
