[package]
name = "mc-fog-test-client"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "test_client"
path = "src/bin/main.rs"

[dependencies]
# mobilecoin
mc-account-keys = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-rand = { workspace = true }
mc-sgx-css = { workspace = true }
mc-transaction-core = { workspace = true }
mc-transaction-extra = { workspace = true }
mc-util-cli = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-keyfile = { workspace = true }
mc-util-metrics = { workspace = true }
mc-util-parse = { workspace = true }
mc-util-telemetry = { workspace = true, features = ["otlp"] }
mc-util-uri = { workspace = true }

# fog
mc-fog-sample-paykit = { workspace = true }
mc-fog-uri = { workspace = true }

# third-party
clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
hex_fmt = { workspace = true }
lazy_static = { workspace = true }
maplit = { workspace = true }
more-asserts = { workspace = true }
once_cell = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
retry = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[dev-dependencies]
mc-common = { workspace = true, features = ["loggers"] }
