[package]
name = "mc-fog-overseer-server"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "fog_overseer_server"
path = "src/bin/main.rs"

[dependencies]
# third-party
clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
lazy_static = { workspace = true }
prometheus = { workspace = true }
retry = { workspace = true }
rocket = { workspace = true, features = ["json"] }
serde = { workspace = true }

# mc
mc-api = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-crypto-keys = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-cli = { workspace = true }
mc-util-metrics = { workspace = true }

# fog
mc-fog-api = { workspace = true }
mc-fog-ingest-client = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-sql-recovery-db = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-uri = { workspace = true }

[dev-dependencies]
# third-party
rand_core = { workspace = true }
rand_hc = { workspace = true }
regex = { workspace = true }
url = { workspace = true }

# mc
mc-ledger-db = { workspace = true }
mc-util-from-random = { workspace = true }
mc-watcher = { workspace = true }

# fog
mc-fog-ingest-enclave = { workspace = true }
mc-fog-ingest-server = { workspace = true }
mc-fog-ingest-server-test-utils = { workspace = true }
mc-fog-test-infra = { workspace = true }
