[package]
name = "mc-fog-ocall-oram-storage-trusted"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# mobilecoin
mc-sgx-compat = { workspace = true }

# mc-oblivious
aligned-cmov = { workspace = true }
balanced-tree-index = { workspace = true }
mc-oblivious-traits = { workspace = true }

# third-party
aes = { workspace = true }
ctr = { workspace = true }
displaydoc = { workspace = true }
lazy_static = { workspace = true, features = ["spin_no_std"] }
rand_core = { workspace = true }
subtle = { workspace = true }

blake2 = { workspace = true }

[dev-dependencies]
lazy_static = { workspace = true }
mc-util-test-helper = { workspace = true }
