[package]
name = "bt-util-metrics"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[features]
default = []
service_metrics = ["dep:tonic"]

[dependencies]
bt-common = { workspace = true, features = ["log"] }

chrono = { workspace = true }
lazy_static = { workspace = true }
prometheus = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true, optional = true }
