[package]
name = "mc-util-metrics"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[features]
default = []
service_metrics = ["dep:grpcio", "dep:prost"]

[dependencies]
mc-common = { workspace = true, features = ["log"] }

chrono = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"], optional = true }
lazy_static = { workspace = true }
prometheus = { workspace = true }
prost = { workspace = true, optional = true }
serde_json = { workspace = true }
