[package]
name = "bth-test-vectors-definitions"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
bth-util-test-vector = { workspace = true }

serde = { workspace = true, features = ["derive"] }
