[package]
name = "bth-util-grpc"
version = "7.1.0"
authors = ["Botho"]
description = "Runtime gRPC Utilities"
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
bth-common = { workspace = true, features = ["loggers"] }
bth-util-build-info = { workspace = true }
bth-util-metrics = { workspace = true, features = ["service_metrics"] }
bth-util-serial = { workspace = true, features = ["std"] }
bth-util-uri = { workspace = true }

base64 = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
cookie = { workspace = true }
displaydoc = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec", "boringssl"] }
hex = { workspace = true }
hex_fmt = { workspace = true }
hmac = { workspace = true }
lazy_static = { workspace = true }
prometheus = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
retry = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
signal-hook = { workspace = true }
subtle = { workspace = true, features = ["i128"] }
zeroize = { workspace = true }

[build-dependencies]
bth-util-build-grpc = { workspace = true }

[dev-dependencies]
libc = { workspace = true }
tempfile = { workspace = true }

bth-crypto-x509-test-vectors = { workspace = true }
