[package]
name = "bth-util-serial"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
# Build everything with std flags turned on.
std = ["serde/std", "postcard/use-std", "serde_with"]
test_utils = []

[dependencies]
prost = { workspace = true, features = ["prost-derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }
postcard = { workspace = true }
serde_with = { workspace = true, features = ["macros"], optional = true }

[dev-dependencies]
serde_json = { workspace = true }
