[package]
name = "mc-fog-ledger-enclave-impl"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
description = "This crate contains the actual implementation of a ledger enclave."
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# mobilecoin
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true }
mc-crypto-ake-enclave = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-rand = { workspace = true }
mc-sgx-compat = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-serial = { workspace = true }
mc-watcher-api = { workspace = true }

# mc-oblivious
aligned-cmov = { workspace = true }
mc-oblivious-map = { workspace = true }
mc-oblivious-ram = { workspace = true }
mc-oblivious-traits = { workspace = true }

# fog
mc-fog-ledger-enclave-api = { workspace = true }
mc-fog-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
mc-common = { workspace = true, features = ["loggers"] }
yare = { workspace = true }
