[package]
name = "mc-fog-ledger-test-infra"
version = "7.1.0"
authors = ["Mobilecoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# mobilecoin
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-untrusted = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-ledger-db = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-transaction-core = { workspace = true }

# fog
mc-fog-ledger-enclave = { workspace = true }
mc-fog-ledger-enclave-api = { workspace = true }
mc-fog-types = { workspace = true }
