[package]
name = "mc-fog-test-infra"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

# This is used by fog-conformance-testing
[[bin]]
name = "init_test_ledger"
path = "src/bin/init_test_ledger.rs"

# This is used by fog-conformance-testing
[[bin]]
name = "add_test_block"
path = "src/bin/add_test_block.rs"

[dependencies]
# from public
mc-account-keys = { workspace = true }
mc-attest-verifier-types = { workspace = true }
mc-blockchain-test-utils = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true }
mc-crypto-hashes = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-ledger-db = { workspace = true, features = ["test_utils"] }
mc-transaction-core = { workspace = true }
mc-util-build-info = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-generate-sample-ledger = { workspace = true }
mc-util-keyfile = { workspace = true }
mc-util-parse = { workspace = true }
mc-watcher = { workspace = true }
mc-watcher-api = { workspace = true }

# from fog
mc-fog-ingest-client = { workspace = true }
mc-fog-kex-rng = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-view-protocol = { workspace = true }

# third party
clap = { workspace = true, features = ["derive", "env"] }
digest = { workspace = true }
hex = { workspace = true }
rand_core = { workspace = true }
rand_hc = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true }
url = { workspace = true }
