[package]
name = "mc-fog-api"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
links = "mc-fog-api"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
displaydoc = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
prost = { workspace = true, features = ["prost-derive"] }

mc-api = { workspace = true }
mc-attest-api = { workspace = true }
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-consensus-api = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-fog-enclave-connection = { workspace = true }
mc-fog-report-api = { workspace = true }
mc-fog-report-types = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-uri = { workspace = true }
mc-util-encodings = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-serial = { workspace = true }
mc-watcher-api = { workspace = true }

[build-dependencies]
mc-util-build-grpc = { workspace = true }
mc-util-build-script = { workspace = true }

cargo-emit = { workspace = true }

[dev-dependencies]
mc-fog-kex-rng = { workspace = true }
mc-fog-report-api-test-utils = { workspace = true }
mc-fog-types = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-test-helper = { workspace = true }
