[package]
name = "bt-util-test-vector"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
