[package]
name = "bth-util-zip-exact"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
description = "An iterator helper"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
default = ["serde"]

[dependencies]
serde = { workspace = true, optional = true }
