[package]
name = "mc-util-test-with-data"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true, features = ["nightly"] }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }
