[package]
name = "bth-crypto-hashes"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
default = ["bth-crypto-digestible/default"]

[dependencies]
bth-crypto-digestible = { workspace = true }

digest = { workspace = true }

blake2 = { workspace = true }
