[package]
name = "mc-crypto-hashes"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
default = ["mc-crypto-digestible/default"]

[dependencies]
mc-crypto-digestible = { workspace = true }

digest = { workspace = true }

blake2 = { workspace = true }
