[package]
name = "mc-fog-uri"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-util-uri = { workspace = true }

[dev-dependencies]
mc-common = { workspace = true }
