[package]
name = "mc-sgx-slog"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
# TODO: Consider making sgx a self-contained workspace and get the value from there.
rust-version = "1.83.0"

[features]
default = []
sgx = []
sgx-sim = []

[dependencies]
cfg-if = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }

mc-common = { workspace = true }

[build-dependencies]
mc-sgx-build = { workspace = true }
