[package]
name = "bt-account-keys-types"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# Botho dependencies
bt-crypto-keys = { workspace = true }
