[package]
name = "mc-consensus-enclave-mock"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
mc-account-keys = { workspace = true }
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-untrusted = { workspace = true }
mc-attest-verifier-types = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true }
mc-consensus-enclave-api = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-multisig = { workspace = true }
mc-rand = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-transaction-core = { workspace = true }
mc-transaction-core-test-utils = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-test-helper = { workspace = true }

mockall = { workspace = true }
