[package]
name = "bt-transaction-signer"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "transaction-signer"
path = "src/main.rs"

[features]
serde = []

[dependencies]
# External dependencies
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
displaydoc = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
subtle = { workspace = true, features = ["i128"] }
tiny-bip39 = { workspace = true }
zeroize = { workspace = true }

# Botho dependencies
bt-account-keys = { workspace = true }
bt-common = { workspace = true, features = ["loggers"] }
bt-core = { workspace = true, features = ["serde", "bip39"] }
bt-core-types = { workspace = true, features = ["serde"] }
bt-crypto-keys = { workspace = true }
bt-crypto-ring-signature = { workspace = true }
bt-crypto-ring-signature-signer = { workspace = true }
bt-transaction-core = { workspace = true }
bt-transaction-summary = { workspace = true }
bt-util-repr-bytes = { workspace = true }
bt-util-serial = { workspace = true }
