[package]
name = "bth-transaction-signer"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "transaction-signer"
path = "src/main.rs"

[features]
serde = []

[dependencies]
# External dependencies
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
log = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Botho dependencies
bth-account-keys = { workspace = true }
bth-core = { workspace = true, features = ["serde", "bip39"] }
bth-crypto-keys = { workspace = true }
bth-crypto-ring-signature = { workspace = true }
bth-crypto-ring-signature-signer = { workspace = true }
bth-transaction-core = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
rand = { workspace = true }
rand_hc = { workspace = true }
bth-util-from-random = { workspace = true }
