[package]
name = "mc-transaction-signer"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "transaction-signer"
path = "src/main.rs"

[features]
serde = []

[dependencies]
# External dependencies
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
displaydoc = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
subtle = { workspace = true, features = ["i128"] }
tiny-bip39 = { workspace = true }
zeroize = { workspace = true }

# MobileCoin dependencies
mc-account-keys = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-core = { workspace = true, features = ["serde", "bip39"] }
mc-core-types = { workspace = true, features = ["serde"] }
mc-crypto-keys = { workspace = true }
mc-crypto-ring-signature = { workspace = true }
mc-crypto-ring-signature-signer = { workspace = true }
mc-transaction-core = { workspace = true }
mc-transaction-summary = { workspace = true }
mc-util-repr-bytes = { workspace = true }
mc-util-serial = { workspace = true }
