[package]
name = "mc-fog-distribution"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "fog-distribution"
path = "src/main.rs"

[dependencies]
mc-account-keys = { workspace = true }
mc-attest-core = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-connection = { workspace = true }
mc-consensus-enclave-measurement = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-ring-signature-signer = { workspace = true }
mc-fog-ingest-enclave-measurement = { workspace = true }
mc-fog-report-connection = { workspace = true }
mc-fog-report-resolver = { workspace = true }
mc-ledger-db = { workspace = true }
mc-transaction-builder = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-cli = { workspace = true }
mc-util-keyfile = { workspace = true }
mc-util-uri = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
crossbeam-channel = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
lazy_static = { workspace = true }
mc-attestation-verifier = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
retry = { workspace = true }
tempfile = { workspace = true }

curve25519-dalek = { workspace = true }

[dev-dependencies]
mc-common = { workspace = true, features = ["loggers"] }
mc-util-generate-sample-ledger = { workspace = true }
