[package]
name = "bt-consensus-scp"
version = "7.1.0"
authors = ["Botho"]
description = "Stellar Consensus Protocol"
edition = "2021"
keywords = ["SCP", "Stellar Consensus Protocol", "Consensus", "Stellar", "Byzantine"]
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
test_utils = ["bt-consensus-scp-types/test_utils"]

[dependencies]
bt-common = { workspace = true, features = ["log"] }
bt-consensus-scp-types = { workspace = true }
bt-crypto-digestible = { workspace = true, features = ["derive"] }
bt-crypto-keys = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-serial = { workspace = true, features = ["std"] }

mockall = { workspace = true }
primitive-types = { workspace = true }
rand = { workspace = true }
rand_hc = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true }

[dev-dependencies]
bt-common = { workspace = true, features = ["loggers"] }
bt-consensus-scp-types = { workspace = true, features = ["test_utils"] }
bt-util-logger-macros = { workspace = true }
bt-util-test-helper = { workspace = true }

crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
maplit = { workspace = true }
serial_test = { workspace = true }
tempfile = { workspace = true }

[[test]]
name = "test_cyclic_networks"
required-features = ["test_utils"]

[[test]]
name = "test_mesh_networks"
required-features = ["test_utils"]

[[test]]
name = "test_metamesh_networks"
required-features = ["test_utils"]
