[package]
name = "mc-crypto-digestible-signature"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
description = "Digestible Signatures"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
alloc = ["mc-crypto-digestible/alloc"]
dalek = ["mc-crypto-digestible/dalek"]
derive = ["mc-crypto-digestible/derive"]
default = ["alloc", "derive", "dalek"]

[dependencies]
mc-crypto-digestible = { workspace = true }

signature = { workspace = true }
