[package]
name = "bt-crypto-digestible-signature"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
description = "Digestible Signatures"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
alloc = ["bt-crypto-digestible/alloc"]
dalek = ["bt-crypto-digestible/dalek"]
derive = ["bt-crypto-digestible/derive"]
default = ["alloc", "derive", "dalek"]

[dependencies]
bt-crypto-digestible = { workspace = true }

signature = { workspace = true }
