[package]
name = "mc-light-client-verifier"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
base64 = { workspace = true }
displaydoc = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_with = { workspace = true, features = ["hex"] }

mc-blockchain-types = { workspace = true }
mc-common = { workspace = true }
mc-consensus-scp-types = { workspace = true }
mc-crypto-digestible = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-transaction-core = { workspace = true }

[dev-dependencies]
mc-consensus-scp-types = { workspace = true, features = ["test_utils"] }
mc-util-from-random = { workspace = true }
mc-util-test-helper = { workspace = true }
