[package]
name = "mc-fog-block-provider"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
description = "Provide blocks from a local or remote ledger database"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
mc-api = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-crypto-keys = { workspace = true }
mc-fog-api = { workspace = true }
mc-ledger-db = { workspace = true }
mc-mobilecoind-api = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-grpc = { workspace = true }
mc-watcher = { workspace = true }
mc-watcher-api = { workspace = true }

displaydoc = { workspace = true }
dyn-clone = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }

[dev-dependencies]
