[package]
name = "bth-ledger-sync"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "ledger-sync-test-app"
path = "src/test_app/main.rs"
required-features = ["test_utils"]

[features]
test_utils = ["bth-consensus-scp/test_utils"]

[dependencies]
bth-account-keys = { workspace = true }
bth-api = { workspace = true }
bth-blockchain-test-utils = { workspace = true }
bth-blockchain-types = { workspace = true }
bth-common = { workspace = true, features = ["log"] }
bth-connection = { workspace = true }
bth-consensus-scp = { workspace = true }
bth-ledger-db = { workspace = true }
bth-transaction-core = { workspace = true }
bth-transaction-core-test-utils = { workspace = true }
bth-util-telemetry = { workspace = true }
bth-util-uri = { workspace = true }

crossbeam-channel = { workspace = true }
displaydoc = { workspace = true }
mockall = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "rustls-tls", "gzip"] }
retry = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
tempfile = { workspace = true }
url = { workspace = true }

[dev-dependencies]
bth-common = { workspace = true, features = ["loggers"] }
bth-connection-test-utils = { workspace = true }
bth-consensus-scp = { workspace = true, features = ["test_utils"] }
bth-ledger-db = { workspace = true, features = ["test_utils"] }
bth-peers-test-utils = { workspace = true }
bth-util-test-helper = { workspace = true }

serde = { workspace = true, features = ["alloc", "derive"] }
