[package]
name = "go-grpc-gateway-testing"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
default-run = "stub"
rust-version = { workspace = true }

[lib]
name = "fog_stub_server"
path = "src/lib.rs"

[[bin]]
name = "stub"
path = "src/bin/main.rs"

[dependencies]
# mobilecoin
mc-attest-core = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-crypto-keys = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-metrics = { workspace = true }
mc-util-uri = { workspace = true }

# fog
mc-fog-report-api = { workspace = true }
mc-fog-report-server = { workspace = true }
mc-fog-report-types = { workspace = true }

# third-party
clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
serde = { workspace = true, features = ["derive"] }
