[package]
name = "mc-fog-sig"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
description = "Verify Fog Signatures"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
mc-account-keys = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-x509-utils = { workspace = true }
mc-fog-report-types = { workspace = true }
mc-fog-sig-authority = { workspace = true }
mc-fog-sig-report = { workspace = true }

displaydoc = { workspace = true }
pem = { workspace = true }
signature = { workspace = true }
x509-signature = { workspace = true }

[dev-dependencies]
mc-attest-verifier-types = { workspace = true }
mc-crypto-x509-test-vectors = { workspace = true }
mc-util-from-random = { workspace = true }

rand_core = { workspace = true }
rand_hc = { workspace = true }
