[package]
name = "bt-ledger-migration"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[[bin]]
name = "bt-ledger-migration"
path = "src/main.rs"

[dependencies]
bt-common = { workspace = true, features = ["loggers"] }
bt-ledger-db = { workspace = true, features = ["migration_support"] }
bt-util-lmdb = { workspace = true }
bt-util-serial = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
lmdb-rkv = { workspace = true }

[build-dependencies]
# Even though this is unused, it needs to be here otherwise Cargo brings in some weird mixture of packages/features that refuses to compile.
# Go figure ¯\_(ツ)_/¯
serde = { workspace = true, features = ["alloc", "derive"] }
