[package]
name = "mc-fog-ocall-oram-storage-testing"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-fog-ocall-oram-storage-untrusted = { workspace = true }

[dev-dependencies]
# mc-oblivious
aligned-cmov = { workspace = true }
mc-oblivious-traits = { workspace = true }

# fog
mc-fog-ocall-oram-storage-trusted = { workspace = true }

# mobilecoin
mc-util-test-helper = { workspace = true }
