[package]
name = "mc-transaction-core-test-utils"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
# MobileCoin dependencies
mc-account-keys = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-multisig = { workspace = true }
mc-crypto-ring-signature-signer = { workspace = true }
mc-rand = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-serial = { workspace = true, features = ["std", "test_utils"] }
