[package]
name = "bth-transaction-core-test-utils"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
# Botho dependencies
bth-account-keys = { workspace = true }
bth-crypto-keys = { workspace = true }
bth-crypto-multisig = { workspace = true }
bth-crypto-ring-signature-signer = { workspace = true }
mc-rand = { workspace = true }
bth-transaction-core = { workspace = true }
bth-util-from-random = { workspace = true }
bth-util-serial = { workspace = true, features = ["std", "test_utils"] }
