[package]
name = "mc-util-parse"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
description = "Helpers for parsing, particularly, for use with Clap and similar"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
hex = { workspace = true }
itertools = { workspace = true }
mc-sgx-css = { workspace = true }
