[package]
name = "mc-fog-ingest-enclave-impl"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
# mobilecoin
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-trusted = { workspace = true }
mc-common = { workspace = true }
mc-crypto-ake-enclave = { workspace = true }
mc-crypto-box = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-rand = { workspace = true }
mc-sgx-compat = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-serial = { workspace = true }

# mc-oblivious
aligned-cmov = { workspace = true }
mc-oblivious-map = { workspace = true }
mc-oblivious-ram = { workspace = true }
mc-oblivious-traits = { workspace = true }

# fog
mc-fog-ingest-enclave-api = { workspace = true }
mc-fog-kex-rng = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-types = { workspace = true }

rand_core = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]

mc-account-keys = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-fog-view-protocol = { workspace = true }
mc-util-logger-macros = { workspace = true }
mc-util-test-helper = { workspace = true }
