[package]
name = "mc-util-lmdb"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
mc-util-serial = { workspace = true, features = ["std"] }

displaydoc = { workspace = true }
lmdb-rkv = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
