[package]
name = "mc-util-seeded-ed25519-key-gen"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
mc-crypto-keys = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-parse = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
pem = { workspace = true }
rand = { workspace = true }
rand_hc = { workspace = true }
