[package]
name = "bth-core-types"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
description = "Botho Core Types"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
serde = ["dep:serde"]
prost = ["dep:prost", "bth-crypto-keys/prost"]

[dependencies]
# External dependencies
curve25519-dalek = { workspace = true }
prost = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
subtle = { workspace = true }
zeroize = { workspace = true }

# Botho dependencies
bth-crypto-keys = { workspace = true }

[dev-dependencies]
bth-util-from-random = { workspace = true }
bth-util-test-helper = { workspace = true }
rand_core = { workspace = true, features = ["getrandom"] }
rand_hc = { workspace = true }
