[package]
name = "mc-fog-ingest-enclave-measurement"
version = "7.1.0"
authors = ["MobileCoin"]
description = "MobileCoin Ingest Enclave - Measurement"
edition = "2021"
links = "ingest_enclave_measurement"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
# Whether the enclave should be built in simulation mode when it needs to be built
sgx-sim = []

[dependencies]
mc-attest-core = { workspace = true }
mc-attestation-verifier = { workspace = true }
mc-sgx-css = { workspace = true }

[build-dependencies]
mc-util-build-enclave = { workspace = true }
mc-util-build-script = { workspace = true }
mc-util-build-sgx = { workspace = true }

cargo-emit = { workspace = true }
