[package]
name = "mc-ledger-db"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
# The migration_support feature exposes some internals that should only be used by the `mc-ledger-migration` tool.
migration_support = []
test_utils = [
    "mc-blockchain-test-utils",
    "mc-transaction-core-test-utils",
    "mc-transaction-builder/test-only",
]

[dependencies]
mc-account-keys = { workspace = true }
mc-blockchain-test-utils = { workspace = true, optional = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-crypto-keys = { workspace = true }
mc-transaction-builder = { workspace = true }
mc-transaction-core = { workspace = true }
mc-transaction-core-test-utils = { workspace = true, optional = true }
mc-util-from-random = { workspace = true }
mc-util-lmdb = { workspace = true }
mc-util-metrics = { workspace = true }
mc-util-serial = { workspace = true, features = ["std"] }
mc-util-telemetry = { workspace = true }
mc-util-test-helper = { workspace = true }

displaydoc = { workspace = true }
lazy_static = { workspace = true }
lmdb-rkv = { workspace = true }
mockall = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
mc-blockchain-test-utils = { workspace = true }
mc-crypto-multisig = { workspace = true }
mc-rand = { workspace = true }
mc-transaction-builder = { workspace = true, features = ["test-only"] }
mc-transaction-core-test-utils = { workspace = true }
