[package]
name = "bt-ledger-db"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
# The migration_support feature exposes some internals that should only be used by the `bt-ledger-migration` tool.
migration_support = []
test_utils = [
    "bt-blockchain-test-utils",
    "bt-transaction-core-test-utils",
    "bt-transaction-builder/test-only",
]

[dependencies]
bt-account-keys = { workspace = true }
bt-blockchain-test-utils = { workspace = true, optional = true }
bt-blockchain-types = { workspace = true }
bt-common = { workspace = true, features = ["log"] }
bt-crypto-keys = { workspace = true }
bt-crypto-ring-signature-signer = { workspace = true }
bt-transaction-builder = { workspace = true }
bt-transaction-core = { workspace = true }
bt-transaction-core-test-utils = { workspace = true, optional = true }
bt-util-from-random = { workspace = true }
bt-util-lmdb = { workspace = true }
bt-util-metrics = { workspace = true }
bt-util-serial = { workspace = true, features = ["std"] }
bt-util-telemetry = { workspace = true }
bt-util-test-helper = { workspace = true }

displaydoc = { workspace = true }
lazy_static = { workspace = true }
lmdb-rkv = { workspace = true }
mockall = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
bt-blockchain-test-utils = { workspace = true }
bt-crypto-multisig = { workspace = true }
mc-rand = { workspace = true }
bt-transaction-builder = { workspace = true, features = ["test-only"] }
bt-transaction-core-test-utils = { workspace = true }
