[package]
name = "bth-ledger-db"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
# The migration_support feature exposes some internals that should only be used by the `bth-ledger-migration` tool.
migration_support = []
test_utils = [
    "bth-blockchain-test-utils",
    "bth-transaction-core-test-utils",
    "bth-transaction-builder/test-only",
]

[dependencies]
bth-account-keys = { workspace = true }
bth-blockchain-test-utils = { workspace = true, optional = true }
bth-blockchain-types = { workspace = true }
bth-common = { workspace = true, features = ["log"] }
bth-crypto-keys = { workspace = true }
bth-crypto-ring-signature-signer = { workspace = true }
bth-transaction-builder = { workspace = true }
bth-transaction-core = { workspace = true }
bth-transaction-core-test-utils = { workspace = true, optional = true }
bth-util-from-random = { workspace = true }
bth-util-lmdb = { workspace = true }
bth-util-metrics = { workspace = true }
bth-util-serial = { workspace = true, features = ["std"] }
bth-util-telemetry = { workspace = true }
bth-util-test-helper = { workspace = true }

displaydoc = { workspace = true }
lmdb-rkv = { workspace = true }
mockall = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
bth-blockchain-test-utils = { workspace = true }
bth-crypto-multisig = { workspace = true }
mc-rand = { workspace = true }
bth-transaction-builder = { workspace = true, features = ["test-only"] }
bth-transaction-core-test-utils = { workspace = true }
