[package]
name = "mc-ledger-distribution"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "ledger-distribution"
path = "src/main.rs"

[dependencies]
mc-api = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-ledger-db = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-telemetry = { workspace = true, features = ["otlp"] }

clap = { workspace = true, features = ["derive", "env"] }
dirs = { workspace = true }
displaydoc = { workspace = true }
prost = { workspace = true }
retry = { workspace = true }
# TODO: Replace with https://github.com/awslabs/aws-sdk-rust when it is ready.
rusoto_core = { workspace = true, features = ["rustls"] }
rusoto_s3 = { workspace = true, features = ["rustls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
url = { workspace = true }

[dev-dependencies]
mc-ledger-db = { workspace = true, features = ["test_utils"] }
mc-util-test-helper = { workspace = true }
tempfile = { workspace = true }
walkdir = { workspace = true }
