[package]
name = "mc-util-vec-map"
version = "7.1.0"
authors = ["MobileCoin"]
description = "A map object based on heapless Vec"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
displaydoc = { workspace = true }
heapless = { workspace = true }
