[package]
name = "mc-sgx-css"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
# TODO: Consider making sgx a self-contained workspace and get the value from there.
rust-version = "1.83.0"

[dependencies]
displaydoc = { workspace = true }
mc-sgx-core-types = { workspace = true }
sha2 = { workspace = true }
