[package]
name = "mc-fog-report-resolver"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
default = []
automock = ["mockall"]

[dependencies]
mc-account-keys = { workspace = true }
mc-attest-verifier = { workspace = true }
mc-fog-ingest-report = { workspace = true }
mc-fog-report-types = { workspace = true }
mc-fog-report-validation = { workspace = true }
mc-fog-sig = { workspace = true }
mc-util-uri = { workspace = true }

mc-attestation-verifier = { workspace = true }
mockall = { workspace = true, optional = true }
serde = { workspace = true, features = ["alloc", "derive"] }
