[package]
name = "mc-fog-report-server"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[lib]
name = "mc_fog_report_server"
path = "src/lib.rs"

[[bin]]
name = "report_server"
path = "src/bin/main.rs"

[dependencies]
mc-attest-core = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-crypto-keys = { workspace = true }
mc-crypto-x509-utils = { workspace = true }
mc-fog-api = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-report-types = { workspace = true }
mc-fog-sig-report = { workspace = true }
mc-fog-sql-recovery-db = { workspace = true }
mc-util-cli = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-metrics = { workspace = true }
mc-util-parse = { workspace = true }
mc-util-uri = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
lazy_static = { workspace = true }
pem = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
signature = { workspace = true }
x509-signature = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

mc-attest-verifier-types = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-crypto-keys = { workspace = true }
mc-crypto-x509-test-vectors = { workspace = true }
mc-fog-test-infra = { workspace = true }
mc-util-from-random = { workspace = true }
