[package]
name = "bth-connection-test-utils"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
bth-blockchain-types = { workspace = true }
bth-connection = { workspace = true }
bth-ledger-db = { workspace = true, features = ["test_utils"] }
bth-transaction-core = { workspace = true }
bth-util-uri = { workspace = true }
