[package]
name = "bt-crypto-keys"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
description = "Botho Diffie-Hellman Key Exchange and Digital Signatures"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
alloc = [
    "base64/alloc",
    "curve25519-dalek/alloc",
    "ed25519-dalek/alloc",
    "bt-crypto-digestible/alloc",
    "bt-crypto-digestible-signature/alloc",
    "bt-util-repr-bytes/alloc",
]
serde = [
    "dep:serde",
    "dep:bt-util-serial",
    "ed25519/serde",
    "curve25519-dalek/serde",
    "ed25519-dalek/serde",
    "bt-util-repr-bytes/serde",
]
prost = ["alloc", "bt-util-repr-bytes/prost"]
default = [
    "alloc",
    "serde",
    "prost",
    "bt-util-repr-bytes/default",
    "curve25519-dalek/default",
    "dep:bt-util-serial",
]

[dependencies]

base64 = { workspace = true }
curve25519-dalek = { workspace = true, features = ["rand_core"] }
digest = { workspace = true }
displaydoc = { workspace = true }
ed25519 = { workspace = true }
ed25519-dalek = { workspace = true, features = ["rand_core", "digest"] }
hex = { workspace = true }
hex_fmt = { workspace = true }

bt-crypto-digestible = { workspace = true, features = ["dalek", "derive"] }
bt-crypto-digestible-signature = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-repr-bytes = { workspace = true }
bt-util-serial = { workspace = true, optional = true }
rand_core = { workspace = true }
rand_hc = { workspace = true }
schnorrkel-og = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
sha2 = { workspace = true }
signature = { workspace = true, features = ["digest"] }
static_assertions = { workspace = true }
subtle = { workspace = true }
x25519-dalek = { workspace = true, features = ["static_secrets"] }
zeroize = { workspace = true }

[dev-dependencies]
bt-crypto-hashes = { workspace = true }
bt-util-test-helper = { workspace = true }

pem = { workspace = true }
rand_hc = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
