[package]
name = "bth-blockchain-types"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
# Botho dependencies
bth-account-keys = { workspace = true }
bth-common = { workspace = true }
bth-consensus-scp-types = { workspace = true }
bth-crypto-digestible = { workspace = true, features = ["dalek", "derive"] }
bth-crypto-digestible-signature = { workspace = true }
bth-crypto-keys = { workspace = true }
bth-crypto-ring-signature = { workspace = true }
bth-transaction-core = { workspace = true }
bth-transaction-types = { workspace = true }
bth-util-from-random = { workspace = true }
bth-util-repr-bytes = { workspace = true }

# External dependencies
displaydoc = { workspace = true }
hex_fmt = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }
zeroize = { workspace = true }

[dev-dependencies]
bth-blockchain-test-utils = { workspace = true }
bth-crypto-digestible-test-utils = { workspace = true }
bth-util-serial = { workspace = true }
bth-util-test-helper = { workspace = true }

rand = { workspace = true }
