[package]
name = "mc-blockchain-types"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
# MobileCoin dependencies
mc-account-keys = { workspace = true }
mc-common = { workspace = true }
mc-consensus-scp-types = { workspace = true }
mc-crypto-digestible = { workspace = true, features = ["dalek", "derive"] }
mc-crypto-digestible-signature = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-ring-signature = { workspace = true }
mc-transaction-core = { workspace = true }
mc-transaction-types = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-repr-bytes = { workspace = true }

# External dependencies
displaydoc = { workspace = true }
hex_fmt = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }
zeroize = { workspace = true }

[dev-dependencies]
mc-blockchain-test-utils = { workspace = true }
mc-crypto-digestible-test-utils = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-test-helper = { workspace = true }

rand = { workspace = true }
