[package]
name = "bth-test-vectors-b58-encodings"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
bth-test-vectors-definitions = { workspace = true }

[build-dependencies]
bth-account-keys = { workspace = true }
bth-api = { workspace = true }
bth-test-vectors-definitions = { workspace = true }
bth-util-test-vector = { workspace = true }
