[package]
name = "mc-test-vectors-b58-encodings"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
mc-test-vectors-definitions = { workspace = true }

[build-dependencies]
mc-account-keys = { workspace = true }
mc-api = { workspace = true }
mc-test-vectors-definitions = { workspace = true }
mc-util-test-vector = { workspace = true }
