[package]
name = "bt-test-vectors-b58-encodings"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
bt-test-vectors-definitions = { workspace = true }

[build-dependencies]
bt-account-keys = { workspace = true }
bt-api = { workspace = true }
bt-test-vectors-definitions = { workspace = true }
bt-util-test-vector = { workspace = true }
