[package]
name = "mc-util-metered-channel"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
mc-util-metrics = { workspace = true }

crossbeam-channel = { workspace = true }
