[package]
name = "bth-util-metered-channel"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
bth-util-metrics = { workspace = true }

crossbeam-channel = { workspace = true }
