[package]
name = "mc-transaction-core"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# External dependencies
aes = { workspace = true }
bulletproofs-og = { workspace = true }
crc = { workspace = true }
ctr = { workspace = true }
curve25519-dalek = { workspace = true }
displaydoc = { workspace = true }
generic-array = { workspace = true, features = ["serde", "more_lengths"] }
hex_fmt = { workspace = true }
hkdf = { workspace = true }
lazy_static = { workspace = true, features = ["spin_no_std"] }
merlin = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand_core = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
sha2 = { workspace = true }
subtle = { workspace = true, features = ["i128"] }
zeroize = { workspace = true }

# MobileCoin dependencies
mc-account-keys = { workspace = true }
mc-common = { workspace = true }
mc-crypto-box = { workspace = true }
mc-crypto-digestible = { workspace = true, features = ["dalek", "derive"] }
mc-crypto-hashes = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-multisig = { workspace = true }
mc-crypto-ring-signature = { workspace = true, features = ["alloc", "serde", "prost"] }
mc-crypto-ring-signature-signer = { workspace = true, features = ["alloc", "serde"] }
mc-transaction-types = { workspace = true, features = ["alloc", "serde", "prost"] }
mc-util-from-random = { workspace = true }
mc-util-repr-bytes = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-u64-ratio = { workspace = true }
mc-util-zip-exact = { workspace = true, features = ["serde"] }

[dev-dependencies]
assert_matches = { workspace = true }

mc-crypto-digestible-test-utils = { workspace = true }
mc-crypto-ring-signature = { workspace = true, features = ["proptest"] }
mc-ledger-db = { workspace = true, features = ["test_utils"] }
mc-transaction-builder = { workspace = true, features = ["test-only"] }
mc-transaction-core-test-utils = { workspace = true }
mc-util-serial = { workspace = true, features = ["std"] }
mc-util-test-helper = { workspace = true }
proptest = { workspace = true, features = ["default-code-coverage"] }
rand = { workspace = true }
