[package]
name = "mc-fog-ingest-client"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[lib]
name = "mc_fog_ingest_client"
path = "src/lib.rs"

[[bin]]
name = "fog_ingest_client"
path = "src/main.rs"

[dependencies]
# third party
clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
hex = { workspace = true }
retry = { workspace = true }
serde_json = { workspace = true }

# root
mc-account-keys = { workspace = true }
mc-api = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-crypto-keys = { workspace = true }
mc-util-cli = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-parse = { workspace = true }
mc-util-uri = { workspace = true }

# fog
mc-fog-api = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-uri = { workspace = true }

[dev-dependencies]
mc-fog-ingest-enclave = { workspace = true }
mc-fog-ingest-server = { workspace = true }
mc-fog-ingest-server-test-utils = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-sql-recovery-db = { workspace = true }
mc-fog-test-infra = { workspace = true }
mc-ledger-db = { workspace = true }
mc-util-from-random = { workspace = true }
mc-watcher = { workspace = true }

# third party
assert_cmd = { workspace = true }
predicates = { workspace = true }
rand = { workspace = true }
