[package]
name = "mc-consensus-service-config"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true }
mc-consensus-scp = { workspace = true }
mc-crypto-digestible = { workspace = true, features = ["derive"] }
mc-crypto-keys = { workspace = true }
mc-crypto-multisig = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-parse = { workspace = true }
mc-util-serial = { workspace = true, features = ["std"] }
mc-util-uri = { workspace = true }

base64 = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
hex = { workspace = true }
pem = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true, features = ["std"] }
serde_with = { workspace = true }
toml = { workspace = true }

