[package]
name = "mc-transaction-types"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
serde = ["dep:serde", "mc-crypto-keys/serde", "mc-crypto-ring-signature/serde"]
prost = ["dep:prost", "mc-crypto-keys/prost", "mc-crypto-ring-signature/prost"]
alloc = ["serde?/alloc", "mc-crypto-digestible/alloc"]

default = ["alloc", "serde", "prost"]

[dependencies]
# External dependencies
crc = { workspace = true }
displaydoc = { workspace = true }
hkdf = { workspace = true }
prost = { workspace = true, features = ["prost-derive"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
sha2 = { workspace = true }
subtle = { workspace = true, features = ["i128"] }
zeroize = { workspace = true }

# MobileCoin dependencies
mc-crypto-digestible = { workspace = true, features = ["dalek", "derive"] }
mc-crypto-hashes = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-ring-signature = { workspace = true }

[dev-dependencies]
mc-crypto-ring-signature = { workspace = true, features = ["proptest"] }
proptest = { workspace = true, features = ["default-code-coverage"] }
