[package]
name = "bt-transaction-types"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
serde = ["dep:serde", "bt-crypto-keys/serde", "bt-crypto-ring-signature/serde"]
prost = ["dep:prost", "bt-crypto-keys/prost", "bt-crypto-ring-signature/prost"]
alloc = ["serde?/alloc", "bt-crypto-digestible/alloc"]

default = ["alloc", "serde", "prost"]

[dependencies]
# External dependencies
crc = { workspace = true }
displaydoc = { workspace = true }
hkdf = { workspace = true }
prost = { workspace = true, features = ["prost-derive"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
sha2 = { workspace = true }
subtle = { workspace = true, features = ["i128"] }
zeroize = { workspace = true }

# Botho dependencies
bt-crypto-digestible = { workspace = true, features = ["dalek", "derive"] }
bt-crypto-hashes = { workspace = true }
bt-crypto-keys = { workspace = true }
bt-crypto-ring-signature = { workspace = true }

[dev-dependencies]
bt-crypto-ring-signature = { workspace = true, features = ["proptest"] }
proptest = { workspace = true, features = ["default-code-coverage"] }
