[package]
name = "mc-crypto-noise"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
mc-crypto-keys = { workspace = true }
mc-util-from-random = { workspace = true }

aead = { workspace = true }
aes-gcm = { workspace = true }
digest = { workspace = true }
displaydoc = { workspace = true }
generic-array = { workspace = true, features = ["serde"] }
hkdf = { workspace = true }
rand_core = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
sha2 = { workspace = true }
subtle = { workspace = true, features = ["i128"] }
zeroize = { workspace = true }

[dev-dependencies]
rand_hc = { workspace = true }
