[package]
name = "bth-crypto-memo-mac"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"

[features]
test-only = []

[dependencies]
# External dependencies
hmac = { workspace = true }
sha2 = { workspace = true }

# Botho dependencies
bth-crypto-keys = { workspace = true }
