[package]
name = "bth-util-grpc-tonic"
version = "7.1.0"
authors = ["Botho"]
description = "Tonic-based gRPC Utilities"
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
bth-common = { workspace = true, features = ["loggers"] }
bth-util-build-info = { workspace = true }
bth-util-metrics = { workspace = true, features = ["service_metrics"] }
bth-util-uri = { workspace = true }

async-trait = { workspace = true }
base64 = { workspace = true }
displaydoc = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hex_fmt = { workspace = true }
hmac = { workspace = true }
bth-util-serial = { workspace = true }
prometheus = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-stream = { workspace = true }
slog = { workspace = true }
tonic = { workspace = true, features = ["transport", "tls", "codegen", "prost"] }
zeroize = { workspace = true }

[build-dependencies]
bth-util-build-grpc-tonic = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
