[package]
name = "mc-crypto-x509-utils"
version = "7.1.0"
authors = ["MobileCoin"]
description = "Verification of X509 certificate chains"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-crypto-keys = { workspace = true }

displaydoc = { workspace = true }
pem = { workspace = true }
x509-signature = { workspace = true }

[dev-dependencies]
mc-crypto-x509-test-vectors = { workspace = true }
