[package]
name = "mc-consensus-pow"
version = "7.1.0"
authors = ["Cadence Foundation"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-blockchain-types = { workspace = true }
mc-transaction-core = { workspace = true }

displaydoc = { workspace = true }

[dev-dependencies]
mc-rand = { workspace = true }
