[package]
name = "bth-crypto-digestible"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
default = ["alloc", "derive", "dalek", "curve25519-dalek/default"]
# Enables support for types in alloc crate
alloc = ["curve25519-dalek/alloc", "ed25519-dalek/alloc"]
# Enables re-export of derive(Digestible) macro
derive = ["bth-crypto-digestible-derive"]
# Enables support for some crypto primitives in dalek crates
dalek = ["curve25519-dalek", "ed25519-dalek", "x25519-dalek"]

[dependencies]
cfg-if = { workspace = true }

# Built-in support for dalek primitives
curve25519-dalek = { workspace = true, optional = true }
ed25519-dalek = { workspace = true, optional = true }
generic-array = { workspace = true }

# For derive support
bth-crypto-digestible-derive = { workspace = true, optional = true }
merlin = { workspace = true }
x25519-dalek = { workspace = true, optional = true }
