[package]
name = "mc-test-vectors-tx-out-records"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
hex = { workspace = true }
mc-test-vectors-definitions = { workspace = true }
rand = { workspace = true }

[build-dependencies]
hex = { workspace = true }
mc-account-keys = { workspace = true }
mc-common = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-fog-ingest-enclave-api = { workspace = true }
mc-fog-ingest-enclave-impl = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-view-protocol = { workspace = true }
mc-oblivious-traits = { workspace = true }
mc-test-vectors-definitions = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-test-vector = { workspace = true }
rand = { workspace = true }
