[package]
name = "bt-test-vectors-tx-out-records"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
hex = { workspace = true }
bt-test-vectors-definitions = { workspace = true }
rand = { workspace = true }

[build-dependencies]
hex = { workspace = true }
bt-account-keys = { workspace = true }
bt-common = { workspace = true }
bt-crypto-keys = { workspace = true }
mc-oblivious-traits = { workspace = true }
bt-test-vectors-definitions = { workspace = true }
bt-transaction-core = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-serial = { workspace = true }
bt-util-test-vector = { workspace = true }
rand = { workspace = true }
