[package]
name = "mc-fog-ingest-server-test-utils"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
# MC/root
mc-blockchain-test-utils = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-crypto-keys = { workspace = true }
mc-ledger-db = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-from-random = { workspace = true }
mc-watcher = { workspace = true }

# fog
mc-fog-block-provider = { workspace = true }
mc-fog-ingest-enclave = { workspace = true }
mc-fog-ingest-server = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-sql-recovery-db = { workspace = true }
mc-fog-test-infra = { workspace = true }
mc-fog-uri = { workspace = true }

# third-party
rand_core = { workspace = true }
rand_hc = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }
