[package]
name = "bt-util-u64-ratio"
version = "7.1.0"
authors = ["Botho"]
description = "A helper for computing with ratios of u64 numbers"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
