[package]
name = "mc-fog-view-enclave-impl"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
static_assertions = { workspace = true }

mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-common = { workspace = true }
mc-crypto-ake-enclave = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-rand = { workspace = true }
mc-sgx-compat = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-util-serial = { workspace = true }

# mc-oblivious
aligned-cmov = { workspace = true }
mc-oblivious-map = { workspace = true }
mc-oblivious-ram = { workspace = true }
mc-oblivious-traits = { workspace = true }

# fog
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-view-enclave-api = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
