[package]
name = "mc-fog-sql-recovery-db"
version = "7.1.0"
authors = ["Mobilecoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[lib]
name = "mc_fog_sql_recovery_db"
path = "src/lib.rs"

[[bin]]
name = "fog-sql-recovery-db-migrations"
path = "src/bin/fog_sql_recovery_db_migrations.rs"

[[bin]]
name = "fog-sql-recovery-db-write-bench"
path = "src/bin/fog_sql_recovery_db_write_bench.rs"

[dependencies]
mc-attest-verifier-types = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-crypto-keys = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-parse = { workspace = true }
mc-util-repr-bytes = { workspace = true }

mc-fog-kex-rng = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-report-types = { workspace = true }
mc-fog-types = { workspace = true }

chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
diesel = { workspace = true, features = ["chrono", "postgres", "r2d2"] }
diesel-derive-enum = { workspace = true, features = ["postgres"] }
diesel_migrations = { workspace = true, features = ["postgres"] }
displaydoc = { workspace = true }
prost = { workspace = true }
r2d2 = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
retry = { workspace = true }
serde = { workspace = true, features = ["derive"] }

# needed for fog-sql-recovery-db-write-bench
mc-fog-test-infra = { workspace = true }

[dev-dependencies]
mc-attest-core = { workspace = true }
mc-attest-verifier-types = { workspace = true }
mc-fog-test-infra = { workspace = true }

mc-crypto-x509-test-vectors = { workspace = true }
mc-util-test-helper = { workspace = true }

rand = { workspace = true }
