[package]
name = "bth-consensus-scp-play"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "scp-play"
path = "src/main.rs"

[dependencies]
bth-common = { workspace = true, features = ["loggers"] }
bth-consensus-scp = { workspace = true, features = ["test_utils"] }
bth-transaction-core = { workspace = true }
bth-util-uri = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
serde_json = { workspace = true }
tracing = { workspace = true }
