[package]
name = "mc-fog-kex-rng"
version = "7.1.0"
authors = ["Mobilecoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-crypto-hashes = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-repr-bytes = { workspace = true }

digest = { workspace = true }
displaydoc = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand_core = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
mc-util-test-helper = { workspace = true }
