[package]
name = "mc-fog-ledger-server"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[lib]
name = "mc_fog_ledger_server"
path = "src/lib.rs"

[[bin]]
name = "ledger_router"
path = "src/bin/router.rs"

[[bin]]
name = "key_image_store"
path = "src/bin/key_image_store.rs"

[dependencies]
mc-attest-api = { workspace = true }
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-crypto-keys = { workspace = true }
mc-ledger-db = { workspace = true }
mc-mobilecoind-api = { workspace = true }
mc-sgx-report-cache-untrusted = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-encodings = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-metrics = { workspace = true }
mc-util-parse = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-telemetry = { workspace = true, features = ["otlp"] }
mc-util-uri = { workspace = true }
mc-watcher = { workspace = true }
mc-watcher-api = { workspace = true }

# fog
mc-fog-api = { workspace = true }
mc-fog-block-provider = { workspace = true }
mc-fog-enclave-connection = { workspace = true }
mc-fog-ledger-enclave = { workspace = true }
mc-fog-ledger-enclave-api = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-uri = { workspace = true }

# third-party
clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
itertools = { workspace = true }
lazy_static = { workspace = true }
mc-attestation-verifier = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
retry = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true }
url = { workspace = true }

[build-dependencies]
mc-util-build-script = { workspace = true }
mc-util-build-sgx = { workspace = true }

[dev-dependencies]
aes-gcm = { workspace = true }
# mobilecoin
mc-account-keys = { workspace = true }
mc-api = { workspace = true }
mc-attest-ake = { workspace = true }
mc-blockchain-test-utils = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-crypto-keys = { workspace = true }
mc-rand = { workspace = true }
mc-util-test-helper = { workspace = true }
mc-util-uri = { workspace = true }

# fog
mc-fog-ledger-connection = { workspace = true }
mc-fog-ledger-enclave-measurement = { workspace = true }
mc-fog-ledger-test-infra = { workspace = true }
mc-fog-test-infra = { workspace = true }
portpicker = { workspace = true }
sha2 = { workspace = true }
stdext = { workspace = true }

# third-party
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }
