[package]
name = "mc-attest-verifier"
version = "7.1.0"
authors = ["MobileCoin"]
description = '''
This crate contains necessary functions and utilities to perform verification of
remote attestation data returned by IAS.
'''
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
default = ["std"]
std = [
    "mc-attest-core/std",
    "mc-common/std",
    "displaydoc/std",
    "mbedtls/std",
]

# This means "use the fake SGX stuff where required"
sgx-sim = []

[dependencies]
mc-attest-core = { workspace = true }
mc-attest-verifier-types = { workspace = true }
mc-common = { workspace = true }
mc-sgx-core-types = { workspace = true }
mc-sgx-css = { workspace = true }
mc-sgx-dcap-types = { workspace = true }
mc-sgx-types = { workspace = true }

cfg-if = { workspace = true }
der = { workspace = true }
displaydoc = { workspace = true }
hex_fmt = { workspace = true }
mbedtls = { workspace = true, features = ["no_std_deps"] }
mc-attestation-verifier = { workspace = true, features = ["mbedtls"] }
serde = { workspace = true, features = ["alloc", "derive"] }
sha2 = { workspace = true }

[build-dependencies]
mc-sgx-core-sys-types = { workspace = true }
mc-util-build-script = { workspace = true }
mc-util-build-sgx = { workspace = true }

cargo-emit = { workspace = true }
chrono = { workspace = true, features = ["now"] }
hex = { workspace = true, features = ["std"] }
lazy_static = { workspace = true }
p256 = { workspace = true, features = ["ecdsa", "pem"] }
rand = { workspace = true }
rand_hc = { workspace = true }

# We use mbedtls to generate certificates for simulation mode
mbedtls = { workspace = true, default-features = true }
mbedtls-sys-auto = { workspace = true }

[dev-dependencies]
mc-attest-untrusted = { workspace = true }
mc-util-encodings = { workspace = true }
p256 = { workspace = true }
textwrap = { workspace = true }
