[package]
name = "mc-fog-sample-paykit"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[[bin]]
name = "balance_check"
path = "src/bin/balance_check.rs"

[[bin]]
name = "sample_paykit_remote_wallet"
path = "src/bin/sample_paykit_remote_wallet.rs"

[dependencies]
# mobilecoin
mc-account-keys = { workspace = true }
mc-api = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-connection = { workspace = true }
mc-consensus-api = { workspace = true }
mc-consensus-enclave-measurement = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-ring-signature = { workspace = true }
mc-crypto-ring-signature-signer = { workspace = true }
mc-rand = { workspace = true }
mc-sgx-css = { workspace = true }
mc-transaction-builder = { workspace = true }
mc-transaction-core = { workspace = true }
mc-transaction-extra = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-keyfile = { workspace = true }
mc-util-telemetry = { workspace = true }
mc-util-uri = { workspace = true }

# fog
mc-fog-api = { workspace = true }
mc-fog-enclave-connection = { workspace = true }
mc-fog-ingest-enclave-measurement = { workspace = true }
mc-fog-ledger-connection = { workspace = true }
mc-fog-ledger-enclave-measurement = { workspace = true }
mc-fog-report-connection = { workspace = true }
mc-fog-report-resolver = { workspace = true }
mc-fog-report-validation = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-uri = { workspace = true }
mc-fog-view-connection = { workspace = true }
mc-fog-view-enclave-measurement = { workspace = true }
mc-fog-view-protocol = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
link-cplusplus = { workspace = true } # This is needed to support building on darwin which only has libc++ and not libstdc++
mc-attestation-verifier = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }

[build-dependencies]
mc-util-build-grpc = { workspace = true }
mc-util-build-script = { workspace = true }

cargo-emit = { workspace = true }

[dev-dependencies]
mc-common = { workspace = true, features = ["loggers"] }
mc-transaction-core-test-utils = { workspace = true }
mc-util-test-helper = { workspace = true }
