[package]
name = "mc-consensus-mint-client"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "mc-consensus-mint-client"
path = "src/bin/main.rs"

[dependencies]
mc-account-keys = { workspace = true }
mc-api = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-consensus-api = { workspace = true }
mc-consensus-mint-client-types = { workspace = true }
mc-consensus-service-config = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-multisig = { workspace = true }
mc-rand = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-parse = { workspace = true }
mc-util-uri = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
hex = { workspace = true, features = ["serde"] }
pem = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
