[package]
name = "bth-crypto-multisig"
version = "7.1.0"
authors = ["Botho"]
description = "Botho multi-signature implementations"
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
bth-crypto-digestible = { workspace = true }
bth-crypto-keys = { workspace = true }

prost = { workspace = true, features = ["prost-derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }

[dev-dependencies]
bth-util-from-random = { workspace = true }
bth-util-serial = { workspace = true }

rand_core = { workspace = true }
rand_hc = { workspace = true }
