[package]
name = "mc-crypto-ake-enclave"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
mc-attest-ake = { workspace = true }
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-trusted = { workspace = true }
mc-attest-verifier = { workspace = true }
mc-common = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-rand = { workspace = true }
mc-sgx-compat = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-serial = { workspace = true }

aes-gcm = { workspace = true }
digest = { workspace = true }
mc-attestation-verifier = { workspace = true }
sha2 = { workspace = true }

[build-dependencies]
mc-sgx-build = { workspace = true }
