[package]
name = "mc-mobilecoind-api"
version = "7.1.0"
authors = ["MobileCoin"]
build = "build.rs"
edition = "2021"
links = "mc-mobilecoind-api"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-api = { workspace = true }
mc-util-uri = { workspace = true }

futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
prost = { workspace = true, features = ["prost-derive"] }

[build-dependencies]
mc-util-build-grpc = { workspace = true }
mc-util-build-script = { workspace = true }

cargo-emit = { workspace = true }

[dev-dependencies]
mc-common = { workspace = true, features = ["loggers"] }
mc-transaction-builder = { workspace = true }

hex_fmt = { workspace = true }
rand = { workspace = true }
