[package]
name = "mc-consensus-enclave"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
description = "MobileCoin Consensus Enclave - Application Code"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-verifier = { workspace = true, features = ["std"] }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true }
mc-consensus-enclave-api = { workspace = true }
mc-consensus-enclave-edl = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-enclave-boundary = { workspace = true }
mc-sgx-panic-edl = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-sgx-slog-edl = { workspace = true }
mc-sgx-types = { workspace = true }
mc-sgx-urts = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-serial = { workspace = true }

[build-dependencies]
mc-util-build-script = { workspace = true }
mc-util-build-sgx = { workspace = true }

cargo-emit = { workspace = true }
pkg-config = { workspace = true }

[dev-dependencies]
mc-attest-ake = { workspace = true }
mc-attest-api = { workspace = true }
mc-consensus-enclave-measurement = { workspace = true }
mc-fog-test-infra = { workspace = true }
mc-ledger-db = { workspace = true, features = ["test_utils"] }
mc-rand = { workspace = true }
mc-sgx-report-cache-untrusted = { workspace = true }
mc-transaction-core-test-utils = { workspace = true }
mc-util-metrics = { workspace = true }

aes-gcm = { workspace = true }
lazy_static = { workspace = true }
sha2 = { workspace = true }
