[package]
name = "bt-blockchain-test-utils"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
bt-blockchain-types = { workspace = true }
bt-common = { workspace = true }
bt-consensus-scp-types = { workspace = true, features = ["test_utils"] }
bt-crypto-keys = { workspace = true }
bt-transaction-core = { workspace = true }
bt-transaction-core-test-utils = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-test-helper = { workspace = true }
