[package]
name = "mc-blockchain-test-utils"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true }
mc-consensus-scp-types = { workspace = true, features = ["test_utils"] }
mc-crypto-keys = { workspace = true }
mc-transaction-core = { workspace = true }
mc-transaction-core-test-utils = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-test-helper = { workspace = true }
