[package]
name = "bth-blockchain-test-utils"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
bth-blockchain-types = { workspace = true }
bth-common = { workspace = true }
bth-consensus-scp-types = { workspace = true, features = ["test_utils"] }
bth-crypto-keys = { workspace = true }
bth-transaction-core = { workspace = true }
bth-transaction-core-test-utils = { workspace = true }
bth-util-from-random = { workspace = true }
bth-util-test-helper = { workspace = true }
