[package]
name = "mc-t3-api"
version = "7.1.0"
edition = "2021"
authors = ["MobileCoin"]
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
prost = { workspace = true }

mc-util-uri = { workspace = true }

[build-dependencies]
cargo-emit = { workspace = true }
mc-util-build-grpc = { workspace = true }
mc-util-build-script = { workspace = true }
