[package]
name = "mc-fog-report-validation-test-utils"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-account-keys = { workspace = true }
mc-fog-report-validation = { workspace = true }
