[package]
name = "mc-crypto-ring-signature-signer"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
serde = [
    "dep:serde",
    "mc-crypto-ring-signature/serde",
    "mc-transaction-types/serde",
    "curve25519-dalek/serde",
]
alloc = ["serde/alloc", "mc-crypto-ring-signature/alloc", "curve25519-dalek/alloc"]

default = ["serde", "alloc", "curve25519-dalek/default"]

[dependencies]
curve25519-dalek = { workspace = true }
# External dependencies
displaydoc = { workspace = true }
generic-array = { workspace = true, features = ["serde", "more_lengths"] }
hex_fmt = { workspace = true }

# MobileCoin dependencies
mc-account-keys = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-ring-signature = { workspace = true, features = ["alloc", "serde", "prost"] }
mc-transaction-types = { workspace = true }
mc-util-serial = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand_core = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
subtle = { workspace = true, features = ["i128"] }
zeroize = { workspace = true }

[dev-dependencies]
mc-crypto-digestible-test-utils = { workspace = true }
mc-rand = { workspace = true }
# Enable all default features not known to break code coverage builds
proptest = { workspace = true, features = ["default-code-coverage"] }
rand = { workspace = true }
rand_hc = { workspace = true }
