[package]
name = "mc-watcher-api"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
displaydoc = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
