[package]
name = "mc-crypto-sig"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
mc-crypto-keys = { workspace = true }

merlin = { workspace = true }
rand_core = { workspace = true }
rand_hc = { workspace = true }
schnorrkel-og = { workspace = true }

[dev-dependencies]
mc-util-from-random = { workspace = true }
mc-util-test-helper = { workspace = true }
