[package]
name = "bth-crypto-sig"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
bth-crypto-keys = { workspace = true }

schnorrkel-og = { workspace = true }

[dev-dependencies]
bth-util-from-random = { workspace = true }
bth-util-test-helper = { workspace = true }
