[package]
name = "mc-consensus-service"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "consensus-service"
path = "src/bin/main.rs"

[dependencies]
mc-attest-api = { workspace = true }
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-verifier = { workspace = true, features = ["std"] }
mc-attest-verifier-types = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-connection = { workspace = true }
mc-consensus-api = { workspace = true }
mc-consensus-enclave = { workspace = true }
mc-consensus-scp = { workspace = true }
mc-consensus-service-config = { workspace = true }
mc-crypto-digestible = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-crypto-multisig = { workspace = true }
mc-ledger-db = { workspace = true }
mc-ledger-sync = { workspace = true }
mc-peers = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-sgx-report-cache-untrusted = { workspace = true }
mc-transaction-builder = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-cli = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-metered-channel = { workspace = true }
mc-util-metrics = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-telemetry = { workspace = true, features = ["otlp"] }
mc-util-uri = { workspace = true }

base64 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
displaydoc = { workspace = true }
fs_extra = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
hex = { workspace = true }
lazy_static = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
retry = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true }

[build-dependencies]
mc-sgx-build = { workspace = true }

[dev-dependencies]
mc-account-keys = { workspace = true }
mc-common = { workspace = true, features = ["loggers"] }
mc-consensus-enclave-mock = { workspace = true }
mc-crypto-ring-signature-signer = { workspace = true }
mc-ledger-db = { workspace = true, features = ["test_utils"] }
mc-peers-test-utils = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-transaction-core-test-utils = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-logger-macros = { workspace = true }

mockall = { workspace = true }
rand_core = { workspace = true }
rand_hc = { workspace = true }
serial_test = { workspace = true }
tempfile = { workspace = true }

curve25519-dalek = { workspace = true }
