[package]
name = "mc-sgx-sync"
version = "7.1.0"
authors = ["MobileCoin"]
license = "GPL-3.0"
readme = "README.md"
# TODO: Consider making sgx a self-contained workspace and get the value from there.
rust-version = "1.83.0"

[features]
default = ["mc-sgx-panic"]
sgx_panic = []

[dependencies]
mc-sgx-panic = { path = "../panic", optional = true }
mc-sgx-types = { path = "../types" }
