[package]
name = "mc-test-vectors-memos"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
# MC Dependencies
mc-test-vectors-definitions = { workspace = true }

# External Dependencies
hex = { workspace = true }
rand = { workspace = true }

[build-dependencies]
# MC Dependencies
mc-account-keys = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-test-vectors-definitions = { workspace = true }
mc-transaction-extra = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-test-vector = { workspace = true }

# External Dependencies
hex = { workspace = true }
rand = { workspace = true }
