[package]
name = "bt-test-vectors-memos"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
# MC Dependencies
bt-test-vectors-definitions = { workspace = true }

# External Dependencies
hex = { workspace = true }
rand = { workspace = true }

[build-dependencies]
# MC Dependencies
bt-account-keys = { workspace = true }
bt-crypto-keys = { workspace = true }
bt-test-vectors-definitions = { workspace = true }
bt-transaction-extra = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-serial = { workspace = true }
bt-util-test-vector = { workspace = true }

# External Dependencies
hex = { workspace = true }
rand = { workspace = true }
