[package]
name = "bth-test-vectors-memos"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
# MC Dependencies
bth-test-vectors-definitions = { workspace = true }

# External Dependencies
hex = { workspace = true }
rand = { workspace = true }

[build-dependencies]
# MC Dependencies
bth-account-keys = { workspace = true }
bth-crypto-keys = { workspace = true }
bth-test-vectors-definitions = { workspace = true }
bth-transaction-extra = { workspace = true }
bth-util-from-random = { workspace = true }
bth-util-serial = { workspace = true }
bth-util-test-vector = { workspace = true }

# External Dependencies
hex = { workspace = true }
rand = { workspace = true }
