[package]
name = "bt-transaction-extra"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# External dependencies
cfg-if = { workspace = true }
displaydoc = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
subtle = { workspace = true }
zeroize = { workspace = true }

# Botho dependencies
bt-account-keys = { workspace = true }
bt-cluster-tax = { workspace = true, optional = true }
bt-core = { workspace = true }
bt-crypto-digestible = { workspace = true, features = ["dalek"] }
bt-crypto-hashes = { workspace = true }
bt-crypto-keys = { workspace = true }
bt-crypto-memo-mac = { workspace = true }
bt-crypto-ring-signature = { workspace = true }
bt-crypto-ring-signature-signer = { workspace = true }
bt-transaction-core = { workspace = true }
bt-transaction-summary = { workspace = true }
bt-transaction-types = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-repr-bytes = { workspace = true }
bt-util-serial = { workspace = true }
bt-util-u64-ratio = { workspace = true }
bt-util-vec-map = { workspace = true }
bt-util-zip-exact = { workspace = true }

curve25519-dalek = { workspace = true }

[features]
default = []
cluster-tax = ["dep:bt-cluster-tax"]

[dev-dependencies]
assert_matches = { workspace = true }
maplit = { workspace = true }
yaml-rust = { workspace = true }

bt-transaction-builder = { workspace = true, features = ["test-only"] }
bt-util-from-random = { workspace = true }
bt-util-test-helper = { workspace = true }
