[package]
name = "bth-transaction-extra"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# External dependencies
cfg-if = { workspace = true }
displaydoc = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
rand = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
subtle = { workspace = true }
zeroize = { workspace = true }

# Botho dependencies
bth-account-keys = { workspace = true }
bth-cluster-tax = { workspace = true, optional = true }
bth-core = { workspace = true }
bth-crypto-digestible = { workspace = true, features = ["dalek"] }
bth-crypto-hashes = { workspace = true }
bth-crypto-keys = { workspace = true }
bth-crypto-memo-mac = { workspace = true }
bth-crypto-ring-signature = { workspace = true }
bth-crypto-ring-signature-signer = { workspace = true }
bth-transaction-core = { workspace = true }
bth-transaction-summary = { workspace = true }
bth-transaction-types = { workspace = true }
bth-util-from-random = { workspace = true }
bth-util-repr-bytes = { workspace = true }
bth-util-serial = { workspace = true }
bth-util-u64-ratio = { workspace = true }
bth-util-vec-map = { workspace = true }
bth-util-zip-exact = { workspace = true }

curve25519-dalek = { workspace = true }

[features]
default = []
cluster-tax = ["dep:bth-cluster-tax"]

[dev-dependencies]
assert_matches = { workspace = true }
maplit = { workspace = true }

bth-transaction-builder = { workspace = true, features = ["test-only"] }
bth-util-from-random = { workspace = true }
bth-util-test-helper = { workspace = true }
