[package]
name = "mc-util-cli"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-util-build-info = { workspace = true }

clap = { workspace = true, features = ["string"] }

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
