[package]
name = "mc-fog-ledger-connection"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
# mobilecoin
mc-api = { workspace = true }
mc-attest-ake = { workspace = true }
mc-attest-core = { workspace = true }
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-crypto-keys = { workspace = true }
mc-crypto-noise = { workspace = true }
mc-rand = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-uri = { workspace = true }

# fog
mc-fog-api = { workspace = true }
mc-fog-enclave-connection = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-uri = { workspace = true }

# third-party
aes-gcm = { workspace = true }
der = { workspace = true }
displaydoc = { workspace = true }
futures = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
mc-attestation-verifier = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
retry = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
mc-common = { workspace = true, features = ["loggers"] }
