[package]
name = "mc-util-grpc-admin-tool"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[[bin]]
name = "mc-util-grpc-admin-tool"
path = "src/bin/main.rs"

[dependencies]
mc-common = { workspace = true, features = ["std"] }
mc-util-grpc = { workspace = true }
mc-util-uri = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
grpcio = { workspace = true, features = ["prost-codec"] }
