[package]
name = "mc-fog-view-server-test-utils"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"

[dependencies]
# MC
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true, features = ["log"] }
mc-transaction-core = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-grpc = { workspace = true }
mc-util-uri = { workspace = true }

# Fog
mc-fog-api = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-sql-recovery-db = { workspace = true }
mc-fog-test-infra = { workspace = true }
mc-fog-types = { workspace = true }
mc-fog-uri = { workspace = true }
mc-fog-view-connection = { workspace = true }
mc-fog-view-enclave = { workspace = true }
mc-fog-view-enclave-measurement = { workspace = true }
mc-fog-view-protocol = { workspace = true }
mc-fog-view-server = { workspace = true }

# Third-party
grpcio = { workspace = true, features = ["prost-codec"] }
mc-attestation-verifier = { workspace = true }
portpicker = { workspace = true }
