[package]
name = "bt-consensus-scp-types"
version = "7.1.0"
authors = ["Botho"]
edition = "2018"
license = "Apache-2.0"
rust-version = { workspace = true }

[features]
default = []
std = ["bt-common/std", "serde/std"]
test_utils = ["bt-util-test-helper", "rand", "rand_hc"]

[dependencies]
bt-common = { workspace = true }
bt-crypto-digestible = { workspace = true, features = ["derive"] }
bt-crypto-keys = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-test-helper = { workspace = true, optional = true }

prost = { workspace = true, features = ["prost-derive"] }
rand = { workspace = true, optional = true }
rand_hc = { workspace = true, optional = true }
serde = { workspace = true, features = ["alloc", "derive"] }

[dev-dependencies]
bt-util-serial = { workspace = true, features = ["std"] }
bt-util-test-helper = { workspace = true }

rand = { workspace = true }
rand_hc = { workspace = true }
