[package]
name = "mc-sgx-css-dump"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
# TODO: Consider making sgx a self-contained workspace and get the value from there.
rust-version = "1.83.0"

[dependencies]
mc-sgx-css = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
hex_fmt = { workspace = true }
