[package]
name = "mc-crypto-digestible-test-utils"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-crypto-digestible = { workspace = true, default-features = true }
serde_json = { workspace = true, features = ["alloc"] }
