[package]
name = "bth-crypto-digestible-test-utils"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
bth-crypto-digestible = { workspace = true, default-features = true }
serde_json = { workspace = true, features = ["alloc"] }
