[package]
name = "mc-attest-verifier-types"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
description = "This crate contains the type definitions for attestation"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
mc-crypto-digestible = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-sgx-core-types = { workspace = true }
mc-sgx-dcap-sys-types = { workspace = true }
mc-sgx-dcap-types = { workspace = true, features = ["alloc"] }
mc-util-encodings = { workspace = true }
mc-util-serial = { workspace = true }

base64 = { workspace = true, features = ["alloc"] }
displaydoc = { workspace = true }
hex = { workspace = true, features = ["alloc"] }
hex_fmt = { workspace = true }
prost = { workspace = true, features = ["prost-derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }
sha2 = { workspace = true }
x509-cert = { workspace = true, features = ["pem"] }

[build-dependencies]
prost-build = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
mc-attest-untrusted = { workspace = true }
mc-util-test-helper = { workspace = true }
