[package]
name = "mc-peers-test-utils"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-blockchain-types = { workspace = true }
mc-common = { workspace = true }
mc-connection = { workspace = true }
mc-consensus-api = { workspace = true }
mc-consensus-scp = { workspace = true, features = ["test_utils"] }
mc-crypto-keys = { workspace = true }
mc-ledger-db = { workspace = true, features = ["test_utils"] }
mc-peers = { workspace = true }
mc-transaction-core = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-uri = { workspace = true }

grpcio = { workspace = true, features = ["prost-codec"] }
hex = { workspace = true }
rand = { workspace = true }
rand_hc = { workspace = true }
retry = { workspace = true }
sha2 = { workspace = true, features = ["asm"] }

[dev-dependencies]
mc-common = { workspace = true, features = ["loggers"] }
