[package]
name = "bth-peers-test-utils"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
bth-blockchain-types = { workspace = true }
bth-common = { workspace = true }
bth-connection = { workspace = true }
bth-consensus-api = { workspace = true }
bth-consensus-scp = { workspace = true, features = ["test_utils"] }
bth-crypto-keys = { workspace = true }
bth-ledger-db = { workspace = true, features = ["test_utils"] }
bth-peers = { workspace = true }
bth-transaction-core = { workspace = true }
bth-util-from-random = { workspace = true }
bth-util-uri = { workspace = true }

hex = { workspace = true }
tonic = { workspace = true }
rand = { workspace = true }
rand_hc = { workspace = true }
retry = { workspace = true }
sha2 = { workspace = true, features = ["asm"] }

[dev-dependencies]
bth-common = { workspace = true, features = ["loggers"] }
