[package]
name = "bt-peers-test-utils"
version = "7.1.0"
authors = ["Botho"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
bt-blockchain-types = { workspace = true }
bt-common = { workspace = true }
bt-connection = { workspace = true }
bt-consensus-api = { workspace = true }
bt-consensus-scp = { workspace = true, features = ["test_utils"] }
bt-crypto-keys = { workspace = true }
bt-ledger-db = { workspace = true, features = ["test_utils"] }
bt-peers = { workspace = true }
bt-transaction-core = { workspace = true }
bt-util-from-random = { workspace = true }
bt-util-uri = { workspace = true }

hex = { workspace = true }
tonic = { workspace = true }
rand = { workspace = true }
rand_hc = { workspace = true }
retry = { workspace = true }
sha2 = { workspace = true, features = ["asm"] }

[dev-dependencies]
bt-common = { workspace = true, features = ["loggers"] }
