[package]
name = "mc-fog-report-validation"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
default = []
automock = ["mockall"]

[dependencies]
mc-account-keys = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-fog-sig = { workspace = true }
mc-util-serial = { workspace = true }
mc-util-uri = { workspace = true }

displaydoc = { workspace = true }
mockall = { workspace = true, optional = true }
