[package]
name = "mc-util-b58-decoder"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[[bin]]
name = "mc-util-b58-decoder"
path = "src/bin/main.rs"

[dependencies]
mc-account-keys = { workspace = true }
mc-api = { workspace = true }

clap = { workspace = true, features = ["derive", "env"] }
hex = { workspace = true }
