[package]
name = "mc-sgx-report-cache-untrusted"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
# TODO: Consider making sgx a self-contained workspace and get the value from there.
rust-version = "1.83.0"

[dependencies]
displaydoc = { workspace = true }
retry = { workspace = true }

mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-untrusted = { workspace = true }
mc-attest-verifier = { workspace = true, features = ["std"] }
mc-common = { workspace = true, features = ["log"] }
mc-sgx-dcap-ql = { workspace = true }
mc-sgx-dcap-quoteverify = { workspace = true }
mc-sgx-dcap-types = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-util-metrics = { workspace = true }
