[package]
name = "mc-fog-view-load-test"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[[bin]]
name = "fog-view-load-test"
path = "src/main.rs"

[dependencies]
# third party
clap = { workspace = true, features = ["derive", "env"] }
ctrlc = { workspace = true }
grpcio = { workspace = true, features = ["prost-codec"] }
rand = { workspace = true }

# mobilecoin
mc-common = { workspace = true, features = ["log"] }
mc-util-cli = { workspace = true }
mc-util-from-random = { workspace = true }
mc-util-grpc = { workspace = true }

# fog
mc-fog-kex-rng = { workspace = true }
mc-fog-uri = { workspace = true }
mc-fog-view-connection = { workspace = true }
mc-fog-view-enclave-measurement = { workspace = true }
mc-fog-view-protocol = { workspace = true }
