[package]
name = "mc-fog-sig-authority"
version = "7.1.0"
authors = ["MobileCoin"]
description = "Create and verify fog authority signatures"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }

[dependencies]
mc-crypto-keys = { workspace = true }

[dev-dependencies]
mc-util-from-random = { workspace = true }

rand_core = { workspace = true }
rand_hc = { workspace = true }
