[package]
name = "mc-fog-ingest-enclave"
version = "7.1.0"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
rust-version = { workspace = true }

[dependencies]
# fog
mc-fog-ingest-enclave-api = { workspace = true }
mc-fog-ingest-enclave-edl = { workspace = true }
mc-fog-kex-rng = { workspace = true }
mc-fog-ocall-oram-storage-edl = { workspace = true }
mc-fog-ocall-oram-storage-untrusted = { workspace = true }
mc-fog-recovery-db-iface = { workspace = true }
mc-fog-types = { workspace = true }

# mobilecoin
mc-attest-core = { workspace = true }
mc-attest-enclave-api = { workspace = true }
mc-attest-verifier = { workspace = true, features = ["std"] }
mc-common = { workspace = true }
mc-crypto-keys = { workspace = true }
mc-enclave-boundary = { workspace = true }
mc-sgx-debug-edl = { workspace = true }
mc-sgx-panic-edl = { workspace = true }
mc-sgx-report-cache-api = { workspace = true }
mc-sgx-slog-edl = { workspace = true }
mc-sgx-types = { workspace = true }
mc-sgx-urts = { workspace = true }
mc-util-serial = { workspace = true }

# third-party
displaydoc = { workspace = true }

[build-dependencies]
mc-util-build-script = { workspace = true }
mc-util-build-sgx = { workspace = true }

cargo-emit = { workspace = true }
pkg-config = { workspace = true }

[dev-dependencies]
mc-common = { workspace = true, features = ["loggers"] }
mc-fog-test-infra = { workspace = true }
mc-rand = { workspace = true }
mc-util-from-random = { workspace = true }

criterion = { workspace = true }
